[server]
host = "localhost"
port = 9090
webroot = "./examples/basic/site"
debug = false
listen = 1024

[files]
not_found = "not_found"
default_page = "index"
log = "./default.log"

[limits]
max_request_size = 10485760
max_upload_size = 52428800
